metadata:
  experiment: 20250930_repcode_d3_simulated_v3_1q_sweep_txt_no_lru
  run: nslru_lstm24x2_eval24_b64_dr0-10_lr0-001_injleak0
  init_weights: null

dataset:
  input_names:
    - "defects"
    - "binary_outcomes"
  basis: "Z"
  distance: 3
  folder_format_name: repcode_d{distance}_r{num_rounds}_s{state}_b{basis}_injleak{injleak}
  train:
    rounds: [1, 2, 3, 4, 5, 6, 7, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41]
    states: ["000", "001", "010", "011", "100", "101", "110", "111"]
    injleak: 0
  val:
    rounds: [1, 2, 3, 4, 5, 6, 7, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41]
    states: ["000", "001", "010", "011", "100", "101", "110", "111"]
    injleak: 0
  test:
    rounds: [1, 2, 3, 4, 5, 7, 8, 10, 13, 16, 21, 26, 33, 42, 53, 68, 87, 108]
    states: ["000", "001", "010", "011", "100", "101", "110", "111"]
    shots: 10730
    injleak: 0
train:
  optimizer:
    learning_rate: 0.001
  loss:
    aux_output: binary_crossentropy
    main_output: binary_crossentropy
  loss_weights:
    main_output: 1.0
    aux_output: 0.5
  metrics:
    aux_output: accuracy
    main_output: accuracy
  callbacks:
    early_stop:
      monitor: val_loss
      mode: min
      min_delta: 0
      patience: 100
    csv_log:
      append: false
    checkpoint:
      monitor: val_loss
      mode: min
      save_best_only: true

  epochs: 500
  batch_size: 64

model:
  type: LSTM

  LSTM:
    units: [24, 24]
    dropout_rates: [0.10, 0.10]

  main_eval:
    units: [24, 1]
    dropout_rates: [0.10, null]
    l2_factor: null

  aux_eval:
    units: [24, 1]
    dropout_rates: [0.10, null]
    l2_factor: null

